In [1]:
import torch


In [2]:
default_tensor = torch.tensor([1.2, 2.3, 3.4])
print(default_tensor.dtype) 

torch.float32


In [3]:
tesor_type = torch.tensor([1.2, 2.5, 4.4], dtype=torch.float64)
print(tesor_type.dtype)


torch.float64


In [8]:
int_tensor = torch.tensor([1.5, 2.7, 3.9], dtype=torch.int32)
print(int_tensor.dtype)
print(int_tensor)

torch.int32
tensor([1, 2, 3], dtype=torch.int32)


In [9]:
int_tensor = torch.tensor([1, 2, 3])
print(int_tensor.dtype)

torch.int64


In [12]:
boolean_tensor = torch.tensor([True, False, True], dtype=torch.bool)
print(boolean_tensor.dtype)
print(boolean_tensor)

torch.bool
tensor([ True, False,  True])


In [11]:
boolean_tensor = torch.tensor([True, False, True])
print(boolean_tensor.dtype)
print(boolean_tensor)

torch.bool
tensor([ True, False,  True])


# converting Data Type 

In [15]:
float_tensor = torch.tensor([1.2, 2.3, 3.4], dtype=torch.float32)
print(float_tensor.dtype)
print(float_tensor)

int_tensor = float_tensor.to(torch.int32)
print(int_tensor.dtype)
print(int_tensor)

intger_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)

boolean_tensor = intger_tensor.to(torch.bool)
print(boolean_tensor.dtype)
print(boolean_tensor)

torch.float32
tensor([1.2000, 2.3000, 3.4000])
torch.int32
tensor([1, 2, 3], dtype=torch.int32)
torch.bool
tensor([True, True, True])


In [ ]:
float32_tensor = torch.ones(1000, dtype=torch.float32)
float64_tensor = torch.ones(1000, dtype=torch.float64)


print(float32_tensor.element_size())
print(float32_tensor.nelement())

print("Memory usage (float32):", float32_tensor.element_size() * float32_tensor.nelement())
print("Memory usage (float64):", float64_tensor.element_size() * float64_tensor.nelement())

4
1000
Memory usage (float32): 4000
Memory usage (float64): 8000


: 