In [1]:
import torch

In [2]:
orignal_tensor = torch.arange(12)
print(orignal_tensor)
print(orignal_tensor.shape)
print(orignal_tensor.nelement())
print(orignal_tensor.ndim)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
torch.Size([12])
12
1


In [3]:
reshaped_tensor = orignal_tensor.reshape(3,4)
print(reshaped_tensor)
print(reshaped_tensor.shape)
print(reshaped_tensor.nelement())
print(reshaped_tensor.ndim)


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
12
2


# Tensor merging 


In [5]:
tensor1 = torch.tensor([[1, 2], [3, 4]])
tensor2 = torch.tensor([[5, 6], [7, 8]])

concat_tensor_row = torch.cat((tensor1, tensor2), dim=0)
concat_tensor_col = torch.cat((tensor1, tensor2), dim=1)
print(concat_tensor_row)
print(concat_tensor_col)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])


# Splitting 

In [10]:
original_tensor = torch.arange(12)
chunks = torch.chunk(orignal_tensor, 6, dim=0)
print(chunks)

for chunk in chunks:
    print(chunk)

(tensor([0, 1]), tensor([2, 3]), tensor([4, 5]), tensor([6, 7]), tensor([8, 9]), tensor([10, 11]))
tensor([0, 1])
tensor([2, 3])
tensor([4, 5])
tensor([6, 7])
tensor([8, 9])
tensor([10, 11])


In [13]:
# splitting 

splitted_tensors = torch.split(orignal_tensor, 5, dim=0)
print(splitted_tensors)

for split in splitted_tensors:
    print(split)

(tensor([0, 1, 2, 3, 4]), tensor([5, 6, 7, 8, 9]), tensor([10, 11]))
tensor([0, 1, 2, 3, 4])
tensor([5, 6, 7, 8, 9])
tensor([10, 11])
