In [2]:
import torch

In [3]:
tensor1 =torch.tensor([1, 2, 3])
tensor2 =torch.tensor([4, 5, 6])


In [4]:
stacked_tensor_dim0 = torch.stack((tensor1, tensor2), dim=0)
print("Shape : ", stacked_tensor_dim0.shape)
print(stacked_tensor_dim0)

print("+"*30)

stacked_tensor_dim1 = torch.stack((tensor1, tensor2) , dim=1)
print("Shape : ", stacked_tensor_dim1.shape)
print(stacked_tensor_dim1)


Shape :  torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])
++++++++++++++++++++++++++++++
Shape :  torch.Size([3, 2])
tensor([[1, 4],
        [2, 5],
        [3, 6]])


In [5]:
tensor3 = torch.tensor([7, 8, 9])

stacked_tensor_dim0_new = torch.stack((tensor1, tensor2, tensor3), dim= 0)
print("Shape : ", stacked_tensor_dim0_new.shape)
print(stacked_tensor_dim0_new)

Shape :  torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [9]:
tensor_1 = torch.tensor([[1,2],[3,4]])
tensor_2 = torch.tensor([[5,6],[7,8]])
print("dimension :", tensor_1.ndim)
stacked_tensor_2d  = torch.stack((tensor_1, tensor_2), dim=0)
print("Shape : ", stacked_tensor_2d.shape)
print("dimension : ", stacked_tensor_2d.ndim)
print(stacked_tensor_2d)

dimension : 2
Shape :  torch.Size([2, 2, 2])
dimension :  3
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


In [10]:
stacked_tensor_2d_dim1  = torch.stack((tensor_1, tensor_2), dim=1)
print("Shape : ", stacked_tensor_2d_dim1.shape)
print("dimension : ", stacked_tensor_2d_dim1.ndim)
print(stacked_tensor_2d_dim1)

Shape :  torch.Size([2, 2, 2])
dimension :  3
tensor([[[1, 2],
         [5, 6]],

        [[3, 4],
         [7, 8]]])


In [11]:
stacked_tensor_2d_dim2  = torch.stack((tensor_1, tensor_2), dim=2)
print("Shape : ", stacked_tensor_2d_dim2.shape)
print("dimension : ", stacked_tensor_2d_dim2.ndim)
print(stacked_tensor_2d_dim2)

Shape :  torch.Size([2, 2, 2])
dimension :  3
tensor([[[1, 5],
         [2, 6]],

        [[3, 7],
         [4, 8]]])


In [14]:
concatenated_tensor_dim0 = torch.cat((tensor_1, tensor_2), dim=0)
print("Shape : ", concatenated_tensor_dim0.shape)
print("Dimension : ", concatenated_tensor_dim0.ndim)
print(concatenated_tensor_dim0)

Shape :  torch.Size([4, 2])
Dimension :  2
tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])


In [15]:
concatenated_tensor_dim1 = torch.cat((tensor_1, tensor_2), dim=1)
print("Shape : ", concatenated_tensor_dim1.shape)
print("Dimension : ", concatenated_tensor_dim1.ndim)
print(concatenated_tensor_dim1)

Shape :  torch.Size([2, 4])
Dimension :  2
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
