In [3]:
import torch

In [4]:
tensor = torch.tensor([[1,2,3],[4,5,6]])
print("Tensor Dimension : ", tensor.ndim)
print("The Shape of Tensor : ", tensor.shape)

Tensor Dimension :  2
The Shape of Tensor :  torch.Size([2, 3])


In [5]:
print("row : ", tensor[0,1])

row :  tensor(2)


In [6]:
print(tensor[0])

tensor([1, 2, 3])


In [8]:
print(tensor[0, 2])

tensor(3)


In [11]:
print(tensor[:, :2])

tensor([[1, 2],
        [4, 5]])


In [14]:
print(tensor[1 , 1:3])

tensor([5, 6])


In [15]:
print(tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# fancy indexing
# (0,2) --> 3
# (1,0) --> 4

print(tensor[[0,1],[2,0]])

tensor([3, 4])
