In [1]:
import torch

In [2]:
matrix = torch.tensor([[1.,2.,3.],
                       [4.,5.,6.],
                       [7.,8.,9.,]])

print ("Original Matrix:\n", matrix)

Original Matrix:
 tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


In [5]:
print(matrix.sum())
print(matrix.min())
print(matrix.max())
print(matrix.mean())
print(matrix.median())
print(matrix.std())
print(matrix.var())

tensor(45.)
tensor(1.)
tensor(9.)
tensor(5.)
tensor(5.)
tensor(2.7386)
tensor(7.5000)


In [6]:
comulative_sum = torch.cumsum(matrix, dim=0)
print(comulative_sum)

tensor([[ 1.,  2.,  3.],
        [ 5.,  7.,  9.],
        [12., 15., 18.]])


In [7]:
compulative_product = torch.cumprod(matrix, dim=0)
print(compulative_product)

tensor([[  1.,   2.,   3.],
        [  4.,  10.,  18.],
        [ 28.,  80., 162.]])
